-- Level Bunker (A–F) & Trafo ESP (A1–A3, B1–B3) untuk kolom Jam 24.00 di logbook.
-- Diinput manual lewat Input Laporan Harian > tab Silo & Fly Ash.
ALTER TABLE daily_report_stock_tank
  ADD COLUMN IF NOT EXISTS bunker_a NUMERIC, ADD COLUMN IF NOT EXISTS bunker_b NUMERIC,
  ADD COLUMN IF NOT EXISTS bunker_c NUMERIC, ADD COLUMN IF NOT EXISTS bunker_d NUMERIC,
  ADD COLUMN IF NOT EXISTS bunker_e NUMERIC, ADD COLUMN IF NOT EXISTS bunker_f NUMERIC,
  ADD COLUMN IF NOT EXISTS trafo_a1 NUMERIC, ADD COLUMN IF NOT EXISTS trafo_a2 NUMERIC,
  ADD COLUMN IF NOT EXISTS trafo_a3 NUMERIC, ADD COLUMN IF NOT EXISTS trafo_b1 NUMERIC,
  ADD COLUMN IF NOT EXISTS trafo_b2 NUMERIC, ADD COLUMN IF NOT EXISTS trafo_b3 NUMERIC;
